### ISSUE TITLE
Sign up form doesn't show errors/warnings

### ISSUE THREAD

**Issue by oskarrough** [radio4000/components#100]
`<r4-form>` used to show warnings/errors/success on forms, but at least for the r4-sign-up/in form it's not working at the moment.

Example. After creating a new account, you have to confirm it via email. This message doesn't appear.

> registered a new account, form submitted, nothing happenned; went to log in, my new user account can't login
should i check my mails? is there an other issue? nah seems i did not got no message; maybe my email already existed in db

**Comment by oskarrough** [comment]
The forms do show errors correctly. The "bug" is that we're not yet sending rendering "success" messages to the form.

In the case of sign up, if we have `res.data.user.id`, it means they user already exists and you're now signed in.

**Comment by 4www** [comment]
Not sure if that's still on but could not really reproduce.

Try to fix the messages of the sign up process, and validation by email.

Also added https://supabase.com/docs/guides/auth/auth-magic-link instead of "reset password" and "resend confirmation link"

ref: https://github.com/radio4000/components/commit/1e0649840f1a3d42c4413c89d333b86f6cdc440b
